# This file was generated by GoReleaser. DO NOT EDIT.
cask "zin" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "ce98cadf4466bd92296f521fa074ced32b864a5201786279842859d108dd5381"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "d981ba44f3d988464849161dce442503a63cd099739d52135598fa2196a26cf8"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c211b9270efd55eb25dd2545fcf7535ec50d0e4517d8bfc4df960a2b61ed73d"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "d2ea356e5dfa941a1663b2656c220c621ec032fbc14480a9791a1d1885436e46"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  name "zin"
  desc "Zinetic Zero Trust CLI"
  homepage "https://cli.zinetic.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zin"]
    end
  end

  # No zap stanza required

end
