# This file was generated by GoReleaser. DO NOT EDIT.
cask "zin" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "90751ebec5e7a8ebed26a716e2ec08ea376970ccea7d044312ec64a58bbd2c0d"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "893d39f35010b89aee7931fe4de3e03b98525c83f74b371231f2be163d55fd85"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  on_linux do
    on_intel do
      sha256 "183af04e5f251bdc9cf9bf3b959e9b39d065b1a30fdf997be837066bc3783718"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "c912f462bc695c02c480ca30fc4a641c456f4758774964d28a8fb5773ea161a4"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  name "zin"
  desc "Zinetic Zero Trust CLI"
  homepage "https://cli.zinetic.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zin"]
    end
  end

  # No zap stanza required

end
