# This file was generated by GoReleaser. DO NOT EDIT.
cask "zin" do
  version "0.1.21"

  on_macos do
    on_intel do
      sha256 "8275d306b128b8bfcee75659b75ba297395a0dc38931f78085aeeb28fcca6c53"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "93f868a997ea9a758ab6fd6ef5d2be721bbf6483e1c9cef1589440e8f7b1fc3c"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1fe7464e2931ea633831b7bf4ce5c93a7d6d810ccdb00bf92977545b7fc876e8"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
    on_arm do
      sha256 "cd1f88fc84253fc469f47b9d7ad743c53be669edd45101209cac097dfbd7f7cd"
      url "https://github.com/Idenity67/zinetic-cli-dist/releases/download/v#{version}/zin_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Idenity67/zinetic-cli-dist/"
    end
  end

  name "zin"
  desc "Zinetic Zero Trust CLI"
  homepage "https://cli.zinetic.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zin"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zin"]
    end
  end

  # No zap stanza required

end
